CREATE INDEX INDEX_PERSONA_NOMBRE ON PERSONA (NOMBRE); -- Buscar persona por NOMBRE
CREATE INDEX INDEX_COMANDA_FECHA ON COMANDA (FECHA); -- Buscar comanda por FECHA 
CREATE INDEX INDEX_CARTA_DISPONIBLE ON CARTA (DISPONIBLE); -- Buscar producto de la carta por DISPONIBILIDAD
CREATE INDEX INDEX_RESTAURANTE_NOMBRE ON RESTAURANTE (NOMBRE); -- Buscar restaurante por NOMBRE