CREATE TABLE RESTAURANTE 
(ID_RESTAURANTE NUMBER,
NIF VARCHAR2(9),
NOMBRE VARCHAR2(40),
DIRECCION VARCHAR2(35),
TELEFONO VARCHAR2(9),
CONSTRAINT PK_RESTAURANTE PRIMARY KEY (ID_RESTAURANTE),
CONSTRAINT UQ_NIF UNIQUE (NIF),
CONSTRAINT UQ_DIRECCION UNIQUE (DIRECCION),
CONSTRAINT UQ_TELEFONO1 UNIQUE (TELEFONO),
CONSTRAINT NN_NIF CHECK (NIF IS NOT NULL),
CONSTRAINT NN_DIRECCION CHECK (DIRECCION IS NOT NULL),
CONSTRAINT NN_TELEFONO CHECK (TELEFONO IS NOT NULL));

CREATE TABLE PROVINCIA
(ID_PROVINCIA NUMBER,
NOMBRE VARCHAR2(25),
CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PROVINCIA),
CONSTRAINT UQ_PROVINCIA UNIQUE (NOMBRE),
CONSTRAINT NN_NOMBRE1 CHECK (NOMBRE IS NOT NULL));

CREATE TABLE TIPO_PRODUCTO 
(ID_TIPO NUMBER,
NOMBRE VARCHAR2(20),
CONSTRAINT PK_TIPO_PROD PRIMARY KEY (ID_TIPO),
CONSTRAINT UQ_TIPO_PRODUCTO UNIQUE (NOMBRE),
CONSTRAINT NN_TIPO_PRODUCTO CHECK (NOMBRE IS NOT NULL));

CREATE TABLE TIPO_EMPLEADO
(ID_TIPO NUMBER,
NOMBRE VARCHAR2(20),
SAL NUMBER(6,2),
CONSTRAINT PK_TIPO_EMP PRIMARY KEY (ID_TIPO),
CONSTRAINT UQ_TIPO_EMPLEADO UNIQUE (NOMBRE),
CONSTRAINT NN_TIPO_EMPLEADO CHECK (NOMBRE IS NOT NULL),
CONSTRAINT CHK_SAL CHECK (SAL >= 900));

CREATE TABLE PERSONA 
(ID_PERSONA NUMBER,
DNI VARCHAR2(9),
NOMBRE VARCHAR2(25),
APELLIDO_1 VARCHAR2(25),
APELLIDO_2 VARCHAR2(25),
DOMICILIO VARCHAR2(20),
TELEFONO VARCHAR2(9),
EMAIL VARCHAR2(30),
ID_PROVINCIA NUMBER,
CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA),
CONSTRAINT FK_PERSONA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA),
CONSTRAINT UQ_DNI UNIQUE (DNI),
CONSTRAINT UQ_TELEFONO2 UNIQUE (TELEFONO),
CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
CONSTRAINT NN_DNI CHECK (DNI IS NOT NULL),
CONSTRAINT NN_NOMBRE3 CHECK (NOMBRE IS NOT NULL),
CONSTRAINT NN_APELLIDO_1 CHECK (APELLIDO_1 IS NOT NULL),
CONSTRAINT NN_APELLIDO_2 CHECK (APELLIDO_2 IS NOT NULL),
CONSTRAINT NN_DOMICILIO CHECK (DOMICILIO IS NOT NULL));

CREATE TABLE EMPLEADO 
(ID_EMPLEADO NUMBER,
IBAN VARCHAR2(24),
NSS VARCHAR2 (12),
ID_PERSONA NUMBER,
ID_TIPO NUMBER,
CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
CONSTRAINT FK_EMPLEADO1 FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA),
CONSTRAINT FK_EMPLEADO2 FOREIGN KEY (ID_TIPO) REFERENCES TIPO_EMPLEADO (ID_TIPO),
CONSTRAINT UQ_IBAN UNIQUE (IBAN),
CONSTRAINT UQ_NSS UNIQUE (NSS),
CONSTRAINT NN_IBAN CHECK (IBAN IS NOT NULL),
CONSTRAINT NN_NSS CHECK (NSS IS NOT NULL));

CREATE TABLE CLIENTE 
(ID_CLIENTE NUMBER,
NUM_TARJETA VARCHAR2(16),
ID_PERSONA NUMBER,
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA),
CONSTRAINT UQ_TARJETA UNIQUE (NUM_TARJETA),
CONSTRAINT NN_TARJETA CHECK (NUM_TARJETA IS NOT NULL));

CREATE TABLE PRODUCTO 
(ID_PRODUCTO NUMBER,
NOMBRE VARCHAR2(40),
ID_TIPO NUMBER,
CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_PRODUCTO (ID_TIPO),
CONSTRAINT UQ_NOMBRE UNIQUE (NOMBRE),
CONSTRAINT NN_NOMBRE2 CHECK (NOMBRE IS NOT NULL));

CREATE TABLE CARTA
(ID_CARTA NUMBER,
DISPONIBLE NUMBER(1) DEFAULT 1,
PVP NUMBER(5,2),
ID_PRODUCTO NUMBER,
ID_RESTAURANTE NUMBER,
CONSTRAINT PK_CARTA PRIMARY KEY (ID_CARTA),
CONSTRAINT FK_CARTA1 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
CONSTRAINT FK_CARTA2 FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE (ID_RESTAURANTE),
CONSTRAINT NN_DISPONIBLE CHECK (DISPONIBLE IS NOT NULL),
CONSTRAINT CHK_DISPONIBLE CHECK (DISPONIBLE IN (0,1)),
CONSTRAINT NN_PVP CHECK (PVP IS NOT NULL));

CREATE TABLE COMANDA 
(ID_COMANDA NUMBER,
FECHA DATE,
PRECIO NUMBER(5,2),
ID_CLIENTE NUMBER,
ID_EMPLEADO NUMBER,
ID_CARTA NUMBER,
CONSTRAINT PK_COMANDA PRIMARY KEY (ID_COMANDA),
CONSTRAINT FK_COMANDA1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
CONSTRAINT FK_COMANDA2 FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
CONSTRAINT FK_COMANDA3 FOREIGN KEY (ID_CARTA) REFERENCES CARTA (ID_CARTA),
CONSTRAINT NN_FECHA CHECK (FECHA IS NOT NULL),
CONSTRAINT NN_PRECIO CHECK (PRECIO IS NOT NULL));

CREATE TABLE LOG_CLIENTE(
ID_LOG NUMBER,
MOMENTO DATE,
ORDEN VARCHAR2(3),
OLD_ID_CLIENTE NUMBER,
NEW_ID_CLIENTE NUMBER,
OLD_NUM_TARJETA VARCHAR2(16),
NEW_NUM_TARJETA VARCHAR2(16),
OLD_ID_PERSONA NUMBER,
NEW_ID_PERSONA NUMBER);

CREATE TABLE LOG_EMPLEADO(
ID_LOG NUMBER,
MOMENTO DATE,
ORDEN VARCHAR2(3),
OLD_ID_EMPLEADO NUMBER,
NEW_ID_EMPLEADO NUMBER,
OLD_IBAN VARCHAR2(24),
NEW_IBAN VARCHAR2(24),
OLD_NSS VARCHAR2(12),
NEW_NSS VARCHAR2(12),
OLD_ID_PERSONA NUMBER,
NEW_ID_PERSONA NUMBER,
OLD_ID_TIPO NUMBER,
NEW_ID_TIPO NUMBER);


CREATE TABLE LOG_PRODUCTO 
(ID_LOG NUMBER,
MOMENTO DATE,
ORDEN VARCHAR2(3),
OLD_ID_PRODUCTO NUMBER,
NEW_ID_PRODUCTO NUMBER,
OLD_NOMBRE VARCHAR2(25),
NEW_NOMBRE VARCHAR(25),
OLD_ID_TIPO NUMBER,
NEW_ID_TIPO NUMBER);

CREATE TABLE LOG_TIPO_PRODUCTO (
ID_LOG NUMBER,
MOMENTO DATE,
ORDEN VARCHAR2(3),
OLD_ID_TIPO NUMBER,
NEW_ID_TIPO NUMBER,
OLD_NOMBRE VARCHAR2(20),
NEW_NOMBRE VARCHAR2(20));

CREATE TABLE LOG_TIPO_EMPLEADO (
ID_LOG NUMBER,
MOMENTO DATE,
ORDEN VARCHAR2(3),
OLD_ID_TIPO NUMBER,
NEW_ID_TIPO NUMBER,
OLD_NOMBRE VARCHAR2(20),
NEW_NOMBRE VARCHAR2(20),
OLD_SAL NUMBER(6,2),
NEW_SAL NUMBER(6,2));

INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (1, 'Álava');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (2, 'Albacete');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (3, 'Alicante');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (4, 'Almería');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (5, 'Asturias');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (6, 'Avila');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (7, 'Badajoz');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (8, 'Barcelona');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (9, 'Burgos');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (10, 'Cáceres');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (11, 'Cádiz');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (12, 'Cantabria');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (13, 'Castellón');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (14, 'Ceuta');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (15, 'Ciudad Real');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (16, 'Córdoba');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (17, 'Cuenca');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (18, 'Gerona');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (19, 'Granada');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (20, 'Guadalajara');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (21, 'Guipúzcoa');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (22, 'Huelva');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (23, 'Huesca');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (24, 'Islas Baleares');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (25, 'Jaén');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (26, 'La Coruña');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (27, 'La Rioja');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (28, 'Las Palmas');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (29, 'León');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (30, 'Lérida');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (31, 'Lugo');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (32, 'Madrid');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (33, 'Málaga');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (34, 'Melilla');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (35, 'Murcia');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (36, 'Navarra');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (37, 'Orense');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (38, 'Palencia');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (39, 'Pontevedra');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (40, 'Salamanca');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (41, 'Santa Cruz de Tenerife');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (42, 'Segovia');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (43, 'Sevilla');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (44, 'Soria');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (45, 'Tarragona');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (46, 'Teruel');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (47, 'Toledo');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (48, 'Valencia');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (49, 'Valladolid');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (50, 'Vizcaya');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (51, 'Zamora');
INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE) VALUES (52, 'Zaragoza');

SELECT * FROM EMPLEADO;

INSERT INTO TIPO_EMPLEADO VALUES(1, 'CAMARERO', 1100);
INSERT INTO TIPO_EMPLEADO VALUES(2, 'COCINERO', 1350);

INSERT INTO PERSONA VALUES(1, '00000001A', 'GONZALO', 'ASTUDILLO', 'LOPEZ', 'C/ TRIANA', '654011081', 'AAA@BBB.COM',43);
INSERT INTO PERSONA VALUES(2, '00000002A', 'MARIO', 'GARCIA', 'LOPEZ', 'C/ PUREZA', '621236545', 'BBB@CCC.COM',42);

INSERT INTO EMPLEADO VALUES(1, 'ES123456789', '141245', 1, 1);
INSERT INTO EMPLEADO VALUES(2, 'ES123456710', '654578', 2, 2);

COMMIT;