CREATE OR REPLACE TRIGGER A_LOG_CLIENTE
AFTER INSERT OR UPDATE OR DELETE ON CLIENTE
FOR EACH ROW
DECLARE
    V_ORDEN VARCHAR(3);
BEGIN

    IF INSERTING THEN 
        V_ORDEN := 'INS';
    END IF;
    IF UPDATING THEN
        V_ORDEN := 'UPD';
    END IF;
    IF DELETING THEN
        V_ORDEN := 'DEL';
    END IF;

    INSERT INTO LOG_CLIENTE
    VALUES (SEQ_LOG_CLIENTE.NEXTVAL, SYSDATE, V_ORDEN, :OLD.ID_CLIENTE, :NEW.ID_CLIENTE, :OLD.NUM_TARJETA, :NEW.NUM_TARJETA, :OLD.ID_PERSONA, :NEW.ID_PERSONA);

END A_LOG_CLIENTE;
/
CREATE OR REPLACE TRIGGER A_LOG_EMPLEADO
AFTER INSERT OR UPDATE OR DELETE ON EMPLEADO
FOR EACH ROW
DECLARE
    V_ORDEN VARCHAR(3);

BEGIN

    IF INSERTING THEN 
        V_ORDEN := 'INS';
    END IF;
    IF UPDATING THEN
        V_ORDEN := 'UPD';
    END IF;
    IF DELETING THEN
        V_ORDEN := 'DEL';
    END IF;

    INSERT INTO LOG_EMPLEADO
    VALUES (SEQ_LOG_EMPLEADO.NEXTVAL, SYSDATE, V_ORDEN, :OLD.ID_EMPLEADO, :NEW.ID_EMPLEADO, :OLD.IBAN, :NEW.IBAN, :OLD.NSS, :NEW.NSS, :OLD.ID_PERSONA, :NEW.ID_PERSONA, :OLD.ID_TIPO, :NEW.ID_TIPO);

END A_LOG_EMPLEADO;
/
CREATE OR REPLACE TRIGGER A_LOG_PRODUCTO
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO
FOR EACH ROW
DECLARE
    V_ORDEN VARCHAR(3);

BEGIN

    IF INSERTING THEN 
        V_ORDEN := 'INS';
    END IF;
    IF UPDATING THEN
        V_ORDEN := 'UPD';
    END IF;
    IF DELETING THEN
        V_ORDEN := 'DEL';
    END IF;

    INSERT INTO LOG_PRODUCTO
    VALUES (SEQ_LOG_PRODUCTO.NEXTVAL, SYSDATE, V_ORDEN, :OLD.ID_PRODUCTO, :NEW.ID_PRODUCTO, :OLD.NOMBRE, :NEW.NOMBRE, :OLD.ID_TIPO, :NEW.ID_TIPO);

END A_LOG_PRODUCTO;
/
CREATE OR REPLACE TRIGGER A_LOG_TIPO_EMPLEADO
AFTER INSERT OR UPDATE OR DELETE ON TIPO_EMPLEADO
FOR EACH ROW
DECLARE
    V_ORDEN VARCHAR(3);

BEGIN

    IF INSERTING THEN 
        V_ORDEN := 'INS';
    END IF;
    IF UPDATING THEN
        V_ORDEN := 'UPD';
    END IF;
    IF DELETING THEN
        V_ORDEN := 'DEL';
    END IF;

    INSERT INTO LOG_TIPO_EMPLEADO
    VALUES (SEQ_LOG_TIPO_EMPLEADO.NEXTVAL, SYSDATE, V_ORDEN, :OLD.ID_TIPO, :NEW.ID_TIPO, :OLD.NOMBRE, :NEW.NOMBRE, :OLD.SAL, :NEW.SAL);

END A_LOG_TIPO_EMPLEADO;
/
CREATE OR REPLACE TRIGGER A_LOG_TIPO_PRODUCTO
AFTER INSERT OR UPDATE OR DELETE ON TIPO_PRODUCTO
FOR EACH ROW
DECLARE
    V_ORDEN VARCHAR(3);

BEGIN

    IF INSERTING THEN 
        V_ORDEN := 'INS';
    END IF;
    IF UPDATING THEN
        V_ORDEN := 'UPD';
    END IF;
    IF DELETING THEN
        V_ORDEN := 'DEL';
    END IF;

    INSERT INTO LOG_PRODUCTO (ID_LOG, MOMENTO, ORDEN, OLD_ID_TIPO, NEW_ID_TIPO, OLD_NOMBRE, NEW_NOMBRE)
    VALUES (SEQ_LOG_PRODUCTO.NEXTVAL, SYSDATE, V_ORDEN, :OLD.ID_TIPO, :NEW.ID_TIPO, :OLD.NOMBRE, :NEW.NOMBRE);

END A_LOG_TIPO_PRODUCTO;